// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as List from "rescript/lib/es6/list.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function findIndex(list, item) {
  var _list = list;
  var _index = 0;
  while(true) {
    var index = _index;
    var list$1 = _list;
    if (list$1) {
      if (list$1.hd === item) {
        return index;
      }
      _index = index + 1 | 0;
      _list = list$1.tl;
      continue ;
    }
    throw {
          RE_EXN_ID: "Not_found",
          Error: new Error()
        };
  };
}

function to_little_endian_32(i) {
  var b1 = i & 255;
  var b2 = (i >>> 8) & 255;
  var b3 = (i >>> 16) & 255;
  var b4 = (i >>> 24) & 255;
  return {
          hd: b1,
          tl: {
            hd: b2,
            tl: {
              hd: b3,
              tl: {
                hd: b4,
                tl: /* [] */0
              }
            }
          }
        };
}

function vadd(a, b) {
  if (a.TAG === /* Vint */0) {
    if (b.TAG === /* Vint */0) {
      return {
              TAG: /* Vint */0,
              _0: a._0 + b._0 | 0
            };
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Demo.res",
            40,
            11
          ],
          Error: new Error()
        };
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "Demo.res",
          40,
          11
        ],
        Error: new Error()
      };
}

function vmul(a, b) {
  if (a.TAG === /* Vint */0) {
    if (b.TAG === /* Vint */0) {
      return {
              TAG: /* Vint */0,
              _0: Math.imul(a._0, b._0)
            };
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Demo.res",
            47,
            11
          ],
          Error: new Error()
        };
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "Demo.res",
          47,
          11
        ],
        Error: new Error()
      };
}

var Ast = {
  vadd: vadd,
  vmul: vmul
};

var last_id = {
  contents: 0
};

function gen_ident(name) {
  last_id.contents = last_id.contents + 1 | 0;
  return {
          name: name,
          stamp: last_id.contents
        };
}

function compile(expr) {
  var compile_inner = function (expr, env) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return {
                  TAG: /* Cst */0,
                  _0: expr._0
                };
      case /* Add */1 :
          return {
                  TAG: /* Add */1,
                  _0: compile_inner(expr._0, env),
                  _1: compile_inner(expr._1, env)
                };
      case /* Sub */2 :
          return {
                  TAG: /* Sub */2,
                  _0: compile_inner(expr._0, env),
                  _1: compile_inner(expr._1, env)
                };
      case /* Mul */3 :
          return {
                  TAG: /* Mul */3,
                  _0: compile_inner(expr._0, env),
                  _1: compile_inner(expr._1, env)
                };
      case /* Var */4 :
          return {
                  TAG: /* Var */4,
                  _0: List.assoc(expr._0, env)
                };
      case /* Let */5 :
          var name = expr._0;
          var ident = gen_ident(name);
          var env_0 = [
            name,
            ident
          ];
          var env$1 = {
            hd: env_0,
            tl: env
          };
          return {
                  TAG: /* Let */5,
                  _0: ident,
                  _1: compile_inner(expr._1, env$1),
                  _2: compile_inner(expr._2, env$1)
                };
      case /* Fn */6 :
          var params = expr._0;
          var idents = Belt_List.map(params, gen_ident);
          var mapping = Belt_List.zip(params, idents);
          return {
                  TAG: /* Fn */6,
                  _0: idents,
                  _1: compile_inner(expr._1, Belt_List.concatMany([
                            mapping,
                            env
                          ]))
                };
      case /* App */7 :
          return {
                  TAG: /* App */7,
                  _0: List.assoc(expr._0, env),
                  _1: Belt_List.map(expr._1, (function (item) {
                          return compile_inner(item, env);
                        }))
                };
      case /* Le */8 :
          return {
                  TAG: /* Le */8,
                  _0: compile_inner(expr._0, env),
                  _1: compile_inner(expr._1, env)
                };
      case /* If */9 :
          return {
                  TAG: /* If */9,
                  _0: compile_inner(expr._0, env),
                  _1: compile_inner(expr._1, env),
                  _2: compile_inner(expr._2, env)
                };
      
    }
  };
  return compile_inner(expr, /* [] */0);
}

var Resolve = {
  last_id: last_id,
  gen_ident: gen_ident,
  compile: compile
};

function print(expr) {
  var go = function (expr) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return String(expr._0);
      case /* Add */1 :
          return "(" + go(expr._0) + ") + (" + go(expr._1) + ")";
      case /* Mul */2 :
          return "(" + go(expr._0) + ") * (" + go(expr._1) + ")";
      case /* Var */3 :
          return "var" + String(expr._0);
      case /* Let */4 :
          return "let v0 = (" + go(expr._0) + ") in (" + go(expr._1) + ")";
      case /* Fn */5 :
          return "fn(" + go(expr._1) + ")";
      case /* App */6 :
          return "app( " + go(expr._0) + Belt_List.reduce(Belt_List.map(expr._1, go), "", (function (list, item) {
                        return list + ", (" + item + "), ";
                      })) + " )";
      
    }
  };
  return go(expr);
}

var Nameless = {
  print: print
};

function find_local_index(env, local_index) {
  var _env = env;
  var _local_index = local_index;
  var _stack_index = 0;
  while(true) {
    var stack_index = _stack_index;
    var local_index$1 = _local_index;
    var env$1 = _env;
    if (env$1) {
      if (env$1.hd) {
        _stack_index = stack_index + 1 | 0;
        _env = env$1.tl;
        continue ;
      }
      if (local_index$1 === 0) {
        return stack_index;
      }
      _stack_index = stack_index + 1 | 0;
      _local_index = local_index$1 - 1 | 0;
      _env = env$1.tl;
      continue ;
    }
    throw {
          RE_EXN_ID: "Not_found",
          Error: new Error()
        };
  };
}

function compile$1(expr) {
  var go = function (expr, env) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return {
                  TAG: /* Cst */0,
                  _0: expr._0
                };
      case /* Add */1 :
          return {
                  TAG: /* Add */1,
                  _0: go(expr._0, env),
                  _1: go(expr._1, {
                        hd: /* Stmp */1,
                        tl: env
                      })
                };
      case /* Mul */2 :
          return {
                  TAG: /* Mul */2,
                  _0: go(expr._0, env),
                  _1: go(expr._1, {
                        hd: /* Stmp */1,
                        tl: env
                      })
                };
      case /* Var */3 :
          return {
                  TAG: /* Var */3,
                  _0: find_local_index(env, expr._0)
                };
      case /* Let */4 :
          return {
                  TAG: /* Let */4,
                  _0: go(expr._0, env),
                  _1: go(expr._1, {
                        hd: /* Slocal */0,
                        tl: env
                      })
                };
      case /* Fn */5 :
          return {
                  TAG: /* Fn */5,
                  _0: go(expr._1, Belt_List.concatMany([
                            Belt_List.makeBy(expr._0, (function (param) {
                                    return /* Slocal */0;
                                  })),
                            env
                          ]))
                };
      case /* App */6 :
          return {
                  TAG: /* App */6,
                  _0: go(expr._0, env),
                  _1: Belt_List.map(expr._1, (function (item) {
                          return go(item, env);
                        }))
                };
      
    }
  };
  return go(expr, /* [] */0);
}

function print$1(expr) {
  var go = function (expr) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return String(expr._0);
      case /* Add */1 :
          return "(" + go(expr._0) + ") + (" + go(expr._1) + ")";
      case /* Mul */2 :
          return "(" + go(expr._0) + ") * (" + go(expr._1) + ")";
      case /* Var */3 :
          return "var" + String(expr._0);
      case /* Let */4 :
          return "let v0 = (" + go(expr._0) + ") in (" + go(expr._1) + ")";
      case /* Fn */5 :
          return "fn(" + go(expr._0) + ")";
      case /* App */6 :
          return "app( " + go(expr._0) + ", " + Belt_List.reduce(Belt_List.map(expr._1, go), "", (function (list, item) {
                        return list + "(" + item + "), ";
                      })) + " )";
      
    }
  };
  return go(expr);
}

var Indexed = {
  find_local_index: find_local_index,
  compile: compile$1,
  print: print$1
};

var ident_main = gen_ident("main");

function find_local_index$1(env, name) {
  var _env = env;
  var _stack_index = 0;
  while(true) {
    var stack_index = _stack_index;
    var env$1 = _env;
    if (env$1) {
      var head = env$1.hd;
      if (head) {
        if (head._0.stamp === name.stamp) {
          return stack_index;
        }
        _stack_index = stack_index + 1 | 0;
        _env = env$1.tl;
        continue ;
      }
      _stack_index = stack_index + 1 | 0;
      _env = env$1.tl;
      continue ;
    }
    throw {
          RE_EXN_ID: "Not_found",
          Error: new Error()
        };
  };
}

function preprocess(expr) {
  var preprocess_rec = function (expr) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return [
                  {
                    TAG: /* Cst */0,
                    _0: expr._0
                  },
                  /* [] */0
                ];
      case /* Add */1 :
          var match = preprocess_rec(expr._0);
          var match$1 = preprocess_rec(expr._1);
          return [
                  {
                    TAG: /* Add */1,
                    _0: match[0],
                    _1: match$1[0]
                  },
                  Belt_List.concatMany([
                        match[1],
                        match$1[1]
                      ])
                ];
      case /* Sub */2 :
          var match$2 = preprocess_rec(expr._0);
          var match$3 = preprocess_rec(expr._1);
          return [
                  {
                    TAG: /* Sub */2,
                    _0: match$2[0],
                    _1: match$3[0]
                  },
                  Belt_List.concatMany([
                        match$2[1],
                        match$3[1]
                      ])
                ];
      case /* Mul */3 :
          var match$4 = preprocess_rec(expr._0);
          var match$5 = preprocess_rec(expr._1);
          return [
                  {
                    TAG: /* Mul */3,
                    _0: match$4[0],
                    _1: match$5[0]
                  },
                  Belt_List.concatMany([
                        match$4[1],
                        match$5[1]
                      ])
                ];
      case /* Var */4 :
          return [
                  {
                    TAG: /* Var */4,
                    _0: expr._0
                  },
                  /* [] */0
                ];
      case /* Let */5 :
          var v1 = expr._1;
          var binding = expr._0;
          if (v1.TAG === /* Fn */6) {
            var match$6 = preprocess_rec(expr._2);
            var match$7 = preprocess_rec(v1._1);
            return [
                    match$6[0],
                    Belt_List.concatMany([
                          {
                            hd: [
                              binding,
                              v1._0,
                              match$7[0]
                            ],
                            tl: match$7[1]
                          },
                          match$6[1]
                        ])
                  ];
          }
          var match$8 = preprocess_rec(v1);
          var match$9 = preprocess_rec(expr._2);
          return [
                  {
                    TAG: /* Let */5,
                    _0: binding,
                    _1: match$8[0],
                    _2: match$9[0]
                  },
                  Belt_List.concatMany([
                        match$8[1],
                        match$9[1]
                      ])
                ];
      case /* Fn */6 :
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "Demo.res",
                  342,
                  20
                ],
                Error: new Error()
              };
      case /* App */7 :
          var match$10 = Belt_List.reduce(expr._1, [
                /* [] */0,
                /* [] */0
              ], (function (param, arg) {
                  var match = preprocess_rec(arg);
                  return [
                          {
                            hd: match[0],
                            tl: param[0]
                          },
                          Belt_List.concatMany([
                                match[1],
                                param[1]
                              ])
                        ];
                }));
          return [
                  {
                    TAG: /* App */6,
                    _0: expr._0,
                    _1: match$10[0]
                  },
                  match$10[1]
                ];
      case /* Le */8 :
          var match$11 = preprocess_rec(expr._0);
          var match$12 = preprocess_rec(expr._1);
          return [
                  {
                    TAG: /* Le */7,
                    _0: match$11[0],
                    _1: match$12[0]
                  },
                  Belt_List.concatMany([
                        match$11[1],
                        match$12[1]
                      ])
                ];
      case /* If */9 :
          var match$13 = preprocess_rec(expr._0);
          var match$14 = preprocess_rec(expr._1);
          var match$15 = preprocess_rec(expr._2);
          return [
                  {
                    TAG: /* If */8,
                    _0: match$13[0],
                    _1: match$14[0],
                    _2: match$15[0]
                  },
                  Belt_List.concatMany([
                        match$13[1],
                        match$14[1],
                        match$15[1]
                      ])
                ];
      
    }
  };
  var match = preprocess_rec(expr);
  return {
          hd: [
            ident_main,
            /* [] */0,
            match[0]
          ],
          tl: match[1]
        };
}

function compile_expr(expr, env) {
  var compile_inner = function (expr, env, if_label) {
    switch (expr.TAG | 0) {
      case /* Cst */0 :
          return {
                  hd: {
                    TAG: /* Cst */0,
                    _0: expr._0
                  },
                  tl: /* [] */0
                };
      case /* Add */1 :
          return Belt_List.concatMany([
                      compile_inner(expr._0, env, if_label + 1 | 0),
                      compile_inner(expr._1, {
                            hd: /* Stmp */0,
                            tl: env
                          }, if_label + 2 | 0),
                      {
                        hd: /* Add */0,
                        tl: /* [] */0
                      }
                    ]);
      case /* Sub */2 :
          return Belt_List.concatMany([
                      compile_inner(expr._0, env, if_label + 1 | 0),
                      compile_inner(expr._1, {
                            hd: /* Stmp */0,
                            tl: env
                          }, if_label + 2 | 0),
                      {
                        hd: /* Sub */1,
                        tl: /* [] */0
                      }
                    ]);
      case /* Mul */3 :
          return Belt_List.concatMany([
                      compile_inner(expr._0, env, if_label + 1 | 0),
                      compile_inner(expr._1, {
                            hd: /* Stmp */0,
                            tl: env
                          }, if_label + 2 | 0),
                      {
                        hd: /* Mul */2,
                        tl: /* [] */0
                      }
                    ]);
      case /* Var */4 :
          return {
                  hd: {
                    TAG: /* Var */1,
                    _0: find_local_index$1(env, expr._0)
                  },
                  tl: /* [] */0
                };
      case /* Let */5 :
          return Belt_List.concatMany([
                      compile_inner(expr._1, env, if_label + 1 | 0),
                      compile_inner(expr._2, {
                            hd: /* Slocal */{
                              _0: expr._0
                            },
                            tl: env
                          }, if_label + 2 | 0),
                      {
                        hd: /* Swap */4,
                        tl: {
                          hd: /* Pop */3,
                          tl: /* [] */0
                        }
                      }
                    ]);
      case /* App */6 :
          var args = expr._1;
          var match = Belt_List.reduceWithIndex(args, [
                /* [] */0,
                env
              ], (function (param, arg, i) {
                  var env = param[1];
                  return [
                          Belt_List.concatMany([
                                param[0],
                                compile_inner(arg, env, (if_label + 1 | 0) + i | 0)
                              ]),
                          {
                            hd: /* Stmp */0,
                            tl: env
                          }
                        ];
                }));
          return Belt_List.concatMany([
                      match[0],
                      {
                        hd: {
                          TAG: /* Call */2,
                          _0: expr._0,
                          _1: Belt_List.length(args)
                        },
                        tl: /* [] */0
                      }
                    ]);
      case /* Le */7 :
          return Belt_List.concatMany([
                      compile_inner(expr._0, env, if_label + 1 | 0),
                      compile_inner(expr._1, {
                            hd: /* Stmp */0,
                            tl: env
                          }, if_label + 2 | 0),
                      {
                        hd: /* Le */5,
                        tl: /* [] */0
                      }
                    ]);
      case /* If */8 :
          var false_label = gen_ident("false");
          var end_of_if = gen_ident("end_of_if");
          return Belt_List.concatMany([
                      compile_inner(expr._0, env, if_label + 1 | 0),
                      {
                        hd: {
                          TAG: /* IfZero */4,
                          _0: false_label
                        },
                        tl: compile_inner(expr._1, env, if_label + 2 | 0)
                      },
                      {
                        hd: {
                          TAG: /* Goto */5,
                          _0: end_of_if
                        },
                        tl: {
                          hd: {
                            TAG: /* Label */6,
                            _0: false_label
                          },
                          tl: compile_inner(expr._2, env, if_label + 3 | 0)
                        }
                      },
                      {
                        hd: {
                          TAG: /* Label */6,
                          _0: end_of_if
                        },
                        tl: /* [] */0
                      }
                    ]);
      
    }
  };
  return compile_inner(expr, env, 0);
}

function compile_fun(fun) {
  var params = fun[1];
  var stack = Belt_List.reverse(Belt_List.map(params, (function (name) {
              return /* Slocal */{
                      _0: name
                    };
            })));
  return Belt_List.concatMany([
              {
                hd: {
                  TAG: /* Label */6,
                  _0: fun[0]
                },
                tl: compile_expr(fun[2], {
                      hd: /* Stmp */0,
                      tl: stack
                    })
              },
              {
                hd: {
                  TAG: /* Ret */3,
                  _0: Belt_List.length(params)
                },
                tl: /* [] */0
              }
            ]);
}

function compile_prog(expr) {
  var expr$1 = compile(expr);
  var fns = Belt_List.flatten(Belt_List.map(preprocess(expr$1), compile_fun));
  return {
          hd: {
            TAG: /* Call */2,
            _0: ident_main,
            _1: 0
          },
          tl: {
            hd: /* Exit */6,
            tl: fns
          }
        };
}

function get_instr_size(instr) {
  if (typeof instr === "number") {
    return 1;
  }
  switch (instr.TAG | 0) {
    case /* Call */2 :
        return 3;
    case /* Cst */0 :
    case /* Var */1 :
    case /* Ret */3 :
    case /* IfZero */4 :
    case /* Goto */5 :
        return 2;
    case /* Label */6 :
        return 0;
    
  }
}

function to_hex(code) {
  return Belt_List.reduce(code, "", (function (sum, item) {
                return sum + Belt_List.reduce(to_little_endian_32(item), "", (function (sum, item) {
                              return sum + ("00" + item.toString(16)).slice(-2);
                            }));
              }));
}

function to_bytecode(instrs) {
  var match = Belt_List.reduce(instrs, [
        /* [] */0,
        0
      ], (function (param, item) {
          var pos = param[1];
          var label_map = param[0];
          if (typeof item === "number" || item.TAG !== /* Label */6) {
            return [
                    label_map,
                    pos + get_instr_size(item) | 0
                  ];
          } else {
            return [
                    {
                      hd: [
                        item._0,
                        pos
                      ],
                      tl: label_map
                    },
                    pos
                  ];
          }
        }));
  var label_map = match[0];
  var compile_instr = function (instr, label_map) {
    if (typeof instr === "number") {
      switch (instr) {
        case /* Add */0 :
            return {
                    hd: 1,
                    tl: /* [] */0
                  };
        case /* Sub */1 :
            return {
                    hd: 11,
                    tl: /* [] */0
                  };
        case /* Mul */2 :
            return {
                    hd: 2,
                    tl: /* [] */0
                  };
        case /* Pop */3 :
            return {
                    hd: 4,
                    tl: /* [] */0
                  };
        case /* Swap */4 :
            return {
                    hd: 5,
                    tl: /* [] */0
                  };
        case /* Le */5 :
            return {
                    hd: 12,
                    tl: /* [] */0
                  };
        case /* Exit */6 :
            return {
                    hd: 10,
                    tl: /* [] */0
                  };
        
      }
    } else {
      switch (instr.TAG | 0) {
        case /* Cst */0 :
            return {
                    hd: 0,
                    tl: {
                      hd: instr._0,
                      tl: /* [] */0
                    }
                  };
        case /* Var */1 :
            return {
                    hd: 3,
                    tl: {
                      hd: instr._0,
                      tl: /* [] */0
                    }
                  };
        case /* Call */2 :
            return {
                    hd: 6,
                    tl: {
                      hd: List.assoc(instr._0, label_map),
                      tl: {
                        hd: instr._1,
                        tl: /* [] */0
                      }
                    }
                  };
        case /* Ret */3 :
            return {
                    hd: 7,
                    tl: {
                      hd: instr._0,
                      tl: /* [] */0
                    }
                  };
        case /* IfZero */4 :
            return {
                    hd: 9,
                    tl: {
                      hd: List.assoc(instr._0, label_map),
                      tl: /* [] */0
                    }
                  };
        case /* Goto */5 :
            return {
                    hd: 8,
                    tl: {
                      hd: List.assoc(instr._0, label_map),
                      tl: /* [] */0
                    }
                  };
        case /* Label */6 :
            return /* [] */0;
        
      }
    }
  };
  return Belt_List.reduce(instrs, /* [] */0, (function (code, instr) {
                var tmp;
                tmp = typeof instr === "number" || instr.TAG !== /* Label */6 ? compile_instr(instr, label_map) : /* [] */0;
                return Belt_List.concatMany([
                            code,
                            tmp
                          ]);
              }));
}

function compile_indexed(expr) {
  switch (expr.TAG | 0) {
    case /* Cst */0 :
        return {
                hd: {
                  TAG: /* Cst */0,
                  _0: expr._0
                },
                tl: /* [] */0
              };
    case /* Add */1 :
        return Belt_List.concatMany([
                    compile_indexed(expr._0),
                    compile_indexed(expr._1),
                    {
                      hd: /* Add */0,
                      tl: /* [] */0
                    }
                  ]);
    case /* Mul */2 :
        return Belt_List.concatMany([
                    compile_indexed(expr._0),
                    compile_indexed(expr._1),
                    {
                      hd: /* Mul */2,
                      tl: /* [] */0
                    }
                  ]);
    case /* Var */3 :
        return {
                hd: {
                  TAG: /* Var */1,
                  _0: expr._0
                },
                tl: /* [] */0
              };
    case /* Let */4 :
        return Belt_List.concatMany([
                    compile_indexed(expr._0),
                    compile_indexed(expr._1),
                    {
                      hd: /* Swap */4,
                      tl: {
                        hd: /* Pop */3,
                        tl: /* [] */0
                      }
                    }
                  ]);
    case /* Fn */5 :
    case /* App */6 :
        throw {
              RE_EXN_ID: "Match_failure",
              _1: [
                "Demo.res",
                494,
                4
              ],
              Error: new Error()
            };
    
  }
}

function print$2(instrs) {
  for(var i = 1 ,i_finish = List.length(instrs); i <= i_finish; ++i){
    var i$1 = List.nth(instrs, i - 1 | 0);
    var instr_text;
    if (typeof i$1 === "number") {
      switch (i$1) {
        case /* Add */0 :
            instr_text = "add";
            break;
        case /* Sub */1 :
            instr_text = "sub";
            break;
        case /* Mul */2 :
            instr_text = "mul";
            break;
        case /* Pop */3 :
            instr_text = "pop";
            break;
        case /* Swap */4 :
            instr_text = "swap";
            break;
        case /* Le */5 :
            instr_text = "le";
            break;
        case /* Exit */6 :
            instr_text = "exit";
            break;
        
      }
    } else {
      switch (i$1.TAG | 0) {
        case /* Cst */0 :
            instr_text = "const " + String(i$1._0);
            break;
        case /* Var */1 :
            instr_text = "var " + String(i$1._0);
            break;
        case /* Call */2 :
            instr_text = "call/" + String(i$1._1) + " " + i$1._0.name;
            break;
        case /* Ret */3 :
            instr_text = "ret " + String(i$1._0);
            break;
        case /* IfZero */4 :
            instr_text = "if_zero " + i$1._0.name;
            break;
        case /* Goto */5 :
            instr_text = "goto " + i$1._0.name;
            break;
        case /* Label */6 :
            instr_text = i$1._0.name + ":";
            break;
        
      }
    }
    console.log(instr_text);
  }
}

var Vm = {
  instr_const: 0,
  instr_add: 1,
  instr_mul: 2,
  instr_var: 3,
  instr_pop: 4,
  instr_swap: 5,
  instr_call: 6,
  instr_ret: 7,
  instr_goto: 8,
  instr_if_zero: 9,
  instr_exit: 10,
  instr_sub: 11,
  instr_le: 12,
  ident_main: ident_main,
  find_local_index: find_local_index$1,
  preprocess: preprocess,
  compile_expr: compile_expr,
  compile_fun: compile_fun,
  compile_prog: compile_prog,
  get_instr_size: get_instr_size,
  to_hex: to_hex,
  to_bytecode: to_bytecode,
  compile_indexed: compile_indexed,
  print: print$2
};

function compile_vm(instrs) {
  var compile_instr = function (instr) {
    if (typeof instr === "number") {
      switch (instr) {
        case /* Add */0 :
            return {
                    hd: {
                      TAG: /* Pop */2,
                      _0: /* Rax */0
                    },
                    tl: {
                      hd: {
                        TAG: /* Pop */2,
                        _0: /* Rbx */1
                      },
                      tl: {
                        hd: {
                          TAG: /* Add */3,
                          _0: /* Rax */0,
                          _1: /* Rbx */1
                        },
                        tl: {
                          hd: {
                            TAG: /* Push */1,
                            _0: /* Rax */0
                          },
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        case /* Mul */2 :
            return {
                    hd: {
                      TAG: /* Pop */2,
                      _0: /* Rax */0
                    },
                    tl: {
                      hd: {
                        TAG: /* Pop */2,
                        _0: /* Rbx */1
                      },
                      tl: {
                        hd: {
                          TAG: /* Mul */4,
                          _0: /* Rbx */1
                        },
                        tl: {
                          hd: {
                            TAG: /* Push */1,
                            _0: /* Rax */0
                          },
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        case /* Pop */3 :
            return {
                    hd: {
                      TAG: /* Pop */2,
                      _0: /* Rax */0
                    },
                    tl: /* [] */0
                  };
        case /* Swap */4 :
            return {
                    hd: {
                      TAG: /* Pop */2,
                      _0: /* Rax */0
                    },
                    tl: {
                      hd: {
                        TAG: /* Pop */2,
                        _0: /* Rbx */1
                      },
                      tl: {
                        hd: {
                          TAG: /* Push */1,
                          _0: /* Rax */0
                        },
                        tl: {
                          hd: {
                            TAG: /* Push */1,
                            _0: /* Rbx */1
                          },
                          tl: /* [] */0
                        }
                      }
                    }
                  };
        default:
          throw {
                RE_EXN_ID: "Match_failure",
                _1: [
                  "Demo.res",
                  535,
                  6
                ],
                Error: new Error()
              };
      }
    } else {
      switch (instr.TAG | 0) {
        case /* Cst */0 :
            return {
                    hd: {
                      TAG: /* Mov */0,
                      _0: /* Rax */0,
                      _1: {
                        TAG: /* Constant */0,
                        _0: instr._0
                      }
                    },
                    tl: {
                      hd: {
                        TAG: /* Push */1,
                        _0: /* Rax */0
                      },
                      tl: /* [] */0
                    }
                  };
        case /* Var */1 :
            return {
                    hd: {
                      TAG: /* Mov */0,
                      _0: /* Rbx */1,
                      _1: {
                        TAG: /* Constant */0,
                        _0: instr._0
                      }
                    },
                    tl: {
                      hd: {
                        TAG: /* Mov */0,
                        _0: /* Rax */0,
                        _1: {
                          TAG: /* RegOffset */3,
                          base: /* Rsp */4,
                          index: /* Rbx */1,
                          scale: 8,
                          disp: 0
                        }
                      },
                      tl: {
                        hd: {
                          TAG: /* Push */1,
                          _0: /* Rax */0
                        },
                        tl: /* [] */0
                      }
                    }
                  };
        default:
          throw {
                RE_EXN_ID: "Match_failure",
                _1: [
                  "Demo.res",
                  535,
                  6
                ],
                Error: new Error()
              };
      }
    }
  };
  var compile_inner = function (instrs) {
    if (!instrs) {
      return /* [] */0;
    }
    var head = instrs.hd;
    if (head === 4) {
      var match = instrs.tl;
      if (match && match.hd === 3) {
        return {
                hd: {
                  TAG: /* Pop */2,
                  _0: /* Rax */0
                },
                tl: {
                  hd: {
                    TAG: /* Pop */2,
                    _0: /* Rbx */1
                  },
                  tl: {
                    hd: {
                      TAG: /* Push */1,
                      _0: /* Rax */0
                    },
                    tl: compile_inner(match.tl)
                  }
                }
              };
      }
      
    }
    return Belt_List.concatMany([
                compile_instr(head),
                compile_inner(instrs.tl)
              ]);
  };
  return Belt_List.concatMany([
              compile_inner(instrs),
              {
                hd: {
                  TAG: /* Pop */2,
                  _0: /* Rax */0
                },
                tl: {
                  hd: /* Ret */0,
                  tl: /* [] */0
                }
              }
            ]);
}

function optimize(instrs) {
  var optimize_inner = function (_instrs) {
    while(true) {
      var instrs = _instrs;
      if (!instrs) {
        return /* [] */0;
      }
      var head = instrs.hd;
      if (typeof head !== "number" && head.TAG === /* Push */1 && head._0 === 0) {
        var match = instrs.tl;
        if (match) {
          var match$1 = match.hd;
          if (typeof match$1 !== "number" && match$1.TAG === /* Pop */2 && match$1._0 === 0) {
            _instrs = match.tl;
            continue ;
          }
          
        }
        
      }
      return {
              hd: head,
              tl: optimize_inner(instrs.tl)
            };
    };
  };
  var _instrs = instrs;
  while(true) {
    var instrs$1 = _instrs;
    var o = optimize_inner(instrs$1);
    if (Belt_List.length(o) === Belt_List.length(instrs$1)) {
      return o;
    }
    _instrs = o;
    continue ;
  };
}

function generate(instrs) {
  var generate_instr = function (instr) {
    if (typeof instr === "number") {
      return {
              hd: 195,
              tl: /* [] */0
            };
    }
    switch (instr.TAG | 0) {
      case /* Mov */0 :
          var i = instr._1;
          var reg = instr._0;
          switch (i.TAG | 0) {
            case /* Constant */0 :
                var i$1 = i._0;
                if (i$1 < 2147483647) {
                  var tmp;
                  switch (reg) {
                    case /* Rax */0 :
                        tmp = 192;
                        break;
                    case /* Rbx */1 :
                        tmp = 195;
                        break;
                    case /* Rcx */2 :
                        tmp = 193;
                        break;
                    case /* Rdx */3 :
                        tmp = 194;
                        break;
                    case /* Rsp */4 :
                        throw {
                              RE_EXN_ID: "Assert_failure",
                              _1: [
                                "Demo.res",
                                591,
                                17
                              ],
                              Error: new Error()
                            };
                    
                  }
                  return {
                          hd: 72,
                          tl: {
                            hd: 199,
                            tl: {
                              hd: tmp,
                              tl: to_little_endian_32(i$1)
                            }
                          }
                        };
                }
                break;
            case /* Reg */1 :
            case /* Addr */2 :
                break;
            case /* RegOffset */3 :
                if (i.scale === 8) {
                  var disp = i.disp;
                  if (disp < 128) {
                    if (i.base >= 4) {
                      var tmp$1;
                      switch (reg) {
                        case /* Rax */0 :
                            tmp$1 = 68;
                            break;
                        case /* Rbx */1 :
                            tmp$1 = 92;
                            break;
                        case /* Rcx */2 :
                            tmp$1 = 76;
                            break;
                        case /* Rdx */3 :
                            tmp$1 = 84;
                            break;
                        case /* Rsp */4 :
                            throw {
                                  RE_EXN_ID: "Assert_failure",
                                  _1: [
                                    "Demo.res",
                                    606,
                                    19
                                  ],
                                  Error: new Error()
                                };
                        
                      }
                      var tmp$2;
                      switch (i.index) {
                        case /* Rax */0 :
                            tmp$2 = 196;
                            break;
                        case /* Rbx */1 :
                            tmp$2 = 220;
                            break;
                        case /* Rcx */2 :
                            tmp$2 = 204;
                            break;
                        case /* Rdx */3 :
                            tmp$2 = 212;
                            break;
                        case /* Rsp */4 :
                            throw {
                                  RE_EXN_ID: "Assert_failure",
                                  _1: [
                                    "Demo.res",
                                    613,
                                    19
                                  ],
                                  Error: new Error()
                                };
                        
                      }
                      return {
                              hd: 72,
                              tl: {
                                hd: 139,
                                tl: {
                                  hd: tmp$1,
                                  tl: {
                                    hd: tmp$2,
                                    tl: {
                                      hd: disp,
                                      tl: /* [] */0
                                    }
                                  }
                                }
                              }
                            };
                    }
                    throw {
                          RE_EXN_ID: "Assert_failure",
                          _1: [
                            "Demo.res",
                            617,
                            15
                          ],
                          Error: new Error()
                        };
                  }
                  
                }
                break;
            
          }
          break;
      case /* Push */1 :
          switch (instr._0) {
            case /* Rax */0 :
                return {
                        hd: 80,
                        tl: /* [] */0
                      };
            case /* Rbx */1 :
                return {
                        hd: 83,
                        tl: /* [] */0
                      };
            case /* Rcx */2 :
                return {
                        hd: 81,
                        tl: /* [] */0
                      };
            case /* Rdx */3 :
                return {
                        hd: 82,
                        tl: /* [] */0
                      };
            case /* Rsp */4 :
                break;
            
          }
          break;
      case /* Pop */2 :
          switch (instr._0) {
            case /* Rax */0 :
                return {
                        hd: 88,
                        tl: /* [] */0
                      };
            case /* Rbx */1 :
                return {
                        hd: 91,
                        tl: /* [] */0
                      };
            case /* Rcx */2 :
                return {
                        hd: 89,
                        tl: /* [] */0
                      };
            case /* Rdx */3 :
                return {
                        hd: 90,
                        tl: /* [] */0
                      };
            case /* Rsp */4 :
                break;
            
          }
          break;
      case /* Add */3 :
          if (instr._0 === 0 && instr._1 === 1) {
            return {
                    hd: 72,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 216,
                        tl: /* [] */0
                      }
                    }
                  };
          }
          break;
      case /* Mul */4 :
          if (instr._0 === 1) {
            return {
                    hd: 72,
                    tl: {
                      hd: 247,
                      tl: {
                        hd: 227,
                        tl: /* [] */0
                      }
                    }
                  };
          }
          break;
      
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Demo.res",
            630,
            13
          ],
          Error: new Error()
        };
  };
  var generate_inner = function (instrs) {
    if (instrs) {
      return Belt_List.concatMany([
                  generate_instr(instrs.hd),
                  generate_inner(instrs.tl)
                ]);
    } else {
      return /* [] */0;
    }
  };
  return generate_inner(instrs);
}

function to_hex$1(code) {
  return Belt_List.reduce(code, "", (function (sum, item) {
                return sum + ("00" + item.toString(16)).slice(-2);
              }));
}

function to_reg_str(reg) {
  switch (reg) {
    case /* Rax */0 :
        return "rax";
    case /* Rbx */1 :
        return "rbx";
    case /* Rcx */2 :
        return "rcx";
    case /* Rdx */3 :
        return "rdx";
    case /* Rsp */4 :
        return "rsp";
    
  }
}

function to_mov_arg_str(reg) {
  switch (reg.TAG | 0) {
    case /* Constant */0 :
        return String(reg._0);
    case /* Reg */1 :
        return to_reg_str(reg._0);
    case /* Addr */2 :
        return "[" + String(reg._0) + "]";
    case /* RegOffset */3 :
        return "[" + to_reg_str(reg.base) + "+" + to_reg_str(reg.index) + "*" + String(reg.scale) + "+" + String(reg.disp) + "]";
    
  }
}

function print$3(instrs) {
  for(var i = 1 ,i_finish = List.length(instrs); i <= i_finish; ++i){
    var reg = List.nth(instrs, i - 1 | 0);
    var instr_text;
    if (typeof reg === "number") {
      instr_text = "ret";
    } else {
      switch (reg.TAG | 0) {
        case /* Mov */0 :
            instr_text = "mov " + to_reg_str(reg._0) + ", " + to_mov_arg_str(reg._1);
            break;
        case /* Push */1 :
            instr_text = "push " + to_reg_str(reg._0);
            break;
        case /* Pop */2 :
            instr_text = "pop " + to_reg_str(reg._0);
            break;
        case /* Add */3 :
            instr_text = "add " + to_reg_str(reg._0) + ", " + to_reg_str(reg._1);
            break;
        case /* Mul */4 :
            instr_text = "mul " + to_reg_str(reg._0);
            break;
        
      }
    }
    console.log(instr_text);
  }
}

var Native = {
  compile_vm: compile_vm,
  optimize: optimize,
  generate: generate,
  to_hex: to_hex$1,
  to_reg_str: to_reg_str,
  to_mov_arg_str: to_mov_arg_str,
  print: print$3
};

var my_expr = {
  TAG: /* Let */5,
  _0: "fib",
  _1: {
    TAG: /* Fn */6,
    _0: {
      hd: "n",
      tl: /* [] */0
    },
    _1: {
      TAG: /* If */9,
      _0: {
        TAG: /* Le */8,
        _0: {
          TAG: /* Var */4,
          _0: "n"
        },
        _1: {
          TAG: /* Cst */0,
          _0: 1
        }
      },
      _1: {
        TAG: /* Cst */0,
        _0: 1
      },
      _2: {
        TAG: /* Add */1,
        _0: {
          TAG: /* App */7,
          _0: "fib",
          _1: {
            hd: {
              TAG: /* Sub */2,
              _0: {
                TAG: /* Var */4,
                _0: "n"
              },
              _1: {
                TAG: /* Cst */0,
                _0: 1
              }
            },
            tl: /* [] */0
          }
        },
        _1: {
          TAG: /* App */7,
          _0: "fib",
          _1: {
            hd: {
              TAG: /* Sub */2,
              _0: {
                TAG: /* Var */4,
                _0: "n"
              },
              _1: {
                TAG: /* Cst */0,
                _0: 2
              }
            },
            tl: /* [] */0
          }
        }
      }
    }
  },
  _2: {
    TAG: /* App */7,
    _0: "fib",
    _1: {
      hd: {
        TAG: /* Cst */0,
        _0: 10
      },
      tl: /* [] */0
    }
  }
};

var instrs2 = compile_prog(my_expr);

console.log("==> single pass:");

print$2(instrs2);

var bytecode = to_hex(to_bytecode(Belt_List.concatMany([
              instrs2,
              {
                hd: /* Exit */6,
                tl: /* [] */0
              }
            ])));

Fs.writeFileSync("bytecode.bin", bytecode, "hex");

export {
  findIndex ,
  to_little_endian_32 ,
  Ast ,
  Resolve ,
  Nameless ,
  Indexed ,
  Vm ,
  Native ,
  my_expr ,
  instrs2 ,
  bytecode ,
}
/* ident_main Not a pure module */
